direcciones_index:
    path:     /
    defaults: { _controller: "UserBundle:Direcciones:index" }
    methods:  GET

direcciones_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:Direcciones:show" }
    methods:  GET

direcciones_new:
    path:     /new
    defaults: { _controller: "UserBundle:Direcciones:new" }
    methods:  [GET, POST]

direcciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:Direcciones:edit" }
    methods:  [GET, POST]

direcciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:Direcciones:delete" }
    methods:  DELETE
