<?php

namespace UserBundle\Repository;

/**
 * DireccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionesRepository extends \Doctrine\ORM\EntityRepository
{
}
