user_usuario:
    resource: "@UserBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

user_direcciones:
        resource: "@UserBundle/Resources/config/routing/direcciones.yml"
        prefix:   /direcciones


user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
